### ISSUE TITLE
ModuleNotFoundError: No module named 'defacer_utils'

### ISSUE THREAD

**Issue by chrisfilo** [AKhazane/DeepDeface#3]
with `deepdefacer-2.0.4[tf]` installed from pypi
```
me@christop ~ $ deepdefacer
Using TensorFlow backend.
Traceback (most recent call last):
  File "c:\users\me\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\Miniconda3\Scripts\deepdefacer.exe\__main__.py", line 5, in <module>
  File "c:\users\me\miniconda3\lib\site-packages\deepdefacer\defacer.py", line 17, in <module>
    from defacer_utils import resize_img, dice_coefficient, resize_img, pre_process_image, get_available_gpus, check_for_resampling, resample_image
ModuleNotFoundError: No module named 'defacer_utils'
```

**Comment by AKhazane** [comment]
That's strange. I'm not running into this on my VM (Linux) or on my Mac. Can you post a screenshot of what exactly gets installed after typing "pip install deepdefacer[tf"?

**Comment by chrisfilo** [comment]
```
me@christop ~ $ pip install --upgrade deepdefacer[tf_gpu]
Collecting deepdefacer[tf_gpu]
  Downloading https://files.pythonhosted.org/packages/76/0e/7a6bcbfcecd0c622976e0ebac8b282f49ef3cc9a5031f2d288ed807aff9d/deepdefacer-2.0.4.tar.gz (5.3MB)
    100% |████████████████████████████████| 5.3MB 1.5MB/s
Requirement already satisfied, skipping upgrade: numpy in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (1.15.4)
Requirement already satisfied, skipping upgrade: keras in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (2.2.4)
Requirement already satisfied, skipping upgrade: nilearn in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (0.5.0)
Requirement already satisfied, skipping upgrade: nibabel in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (2.3.1)
Requirement already satisfied, skipping upgrade: sklearn in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (0.0)
Requirement already satisfied, skipping upgrade: scipy in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (1.1.0)
Requirement already satisfied, skipping upgrade: ipython in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (7.2.0)
Requirement already satisfied, skipping upgrade: matplotlib in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (3.0.1)
Collecting SimpleITK (from deepdefacer[tf_gpu])
  Downloading https://files.pythonhosted.org/packages/00/8d/a3e971b031088e1873643923684ee865a4f596146e601f40383cb0551302/SimpleITK-1.2.0-cp37-cp37m-win_amd64.whl (28.1MB)
    100% |████████████████████████████████| 28.1MB 656kB/s
Requirement already satisfied, skipping upgrade: tensorflow-gpu>=1.0.0 in c:\users\me\miniconda3\lib\site-packages (from deepdefacer[tf_gpu]) (1.12.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in c:\users\me\miniconda3\lib\site-packages (from keras->deepdefacer[tf_gpu]) (1.0.5)
Requirement already satisfied, skipping upgrade: h5py in c:\users\me\miniconda3\lib\site-packages (from keras->deepdefacer[tf_gpu]) (2.8.0)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in c:\users\me\miniconda3\lib\site-packages (from keras->deepdefacer[tf_gpu]) (1.11.0)
Requirement already satisfied, skipping upgrade: pyyaml in c:\users\me\miniconda3\lib\site-packages (from keras->deepdefacer[tf_gpu]) (3.13)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in c:\users\me\miniconda3\lib\site-packages (from keras->deepdefacer[tf_gpu]) (1.0.6)
Requirement already satisfied, skipping upgrade: scikit-learn in c:\users\me\miniconda3\lib\site-packages (from sklearn->deepdefacer[tf_gpu]) (0.20.1)
Requirement already satisfied, skipping upgrade: prompt-toolkit<2.1.0,>=2.0.0 in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (2.0.7)
Requirement already satisfied, skipping upgrade: backcall in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (0.1.0)
Requirement already satisfied, skipping upgrade: decorator in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (4.3.0)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (0.13.1)
Requirement already satisfied, skipping upgrade: traitlets>=4.2 in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (4.3.2)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (40.6.2) Requirement already satisfied, skipping upgrade: colorama; sys_platform == "win32" in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (0.4.0)
Requirement already satisfied, skipping upgrade: pickleshare in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (0.7.5)
Requirement already satisfied, skipping upgrade: pygments in c:\users\me\miniconda3\lib\site-packages (from ipython->deepdefacer[tf_gpu]) (2.2.0)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in c:\users\me\miniconda3\lib\site-packages (from matplotlib->deepdefacer[tf_gpu]) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in c:\users\me\miniconda3\lib\site-packages (from matplotlib->deepdefacer[tf_gpu]) (1.0.1)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\me\miniconda3\lib\site-packages (from matplotlib->deepdefacer[tf_gpu]) (2.3.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in c:\users\me\miniconda3\lib\site-packages (from matplotlib->deepdefacer[tf_gpu]) (2.7.5)
Requirement already satisfied, skipping upgrade: astor>=0.6.0 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (0.6.2)
Requirement already satisfied, skipping upgrade: tensorboard<1.13.0,>=1.12.0 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (1.12.1)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (1.1.0)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (1.12.0)
Requirement already satisfied, skipping upgrade: gast>=0.2.0 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (0.2.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.1 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (3.6.1)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (0.32.3)
Requirement already satisfied, skipping upgrade: absl-py>=0.1.6 in c:\users\me\miniconda3\lib\site-packages (from tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (0.2.2)
Requirement already satisfied, skipping upgrade: wcwidth in c:\users\me\miniconda3\lib\site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->deepdefacer[tf_gpu]) (0.1.7)
Requirement already satisfied, skipping upgrade: parso>=0.3.0 in c:\users\me\miniconda3\lib\site-packages (from jedi>=0.10->ipython->deepdefacer[tf_gpu]) (0.3.1)
Requirement already satisfied, skipping upgrade: ipython-genutils in c:\users\me\miniconda3\lib\site-packages (from traitlets>=4.2->ipython->deepdefacer[tf_gpu]) (0.2.0)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.10 in c:\users\me\miniconda3\lib\site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (0.14.1)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in c:\users\me\miniconda3\lib\site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow-gpu>=1.0.0->deepdefacer[tf_gpu]) (2.6.11)
Building wheels for collected packages: deepdefacer
  Running setup.py bdist_wheel for deepdefacer ... done
  Stored in directory: C:\Users\me\AppData\Local\pip\Cache\wheels\d4\f9\38\bdc5fa82db07d68dd982dab88e3e8b6c5551d7f3f175c2a33f
Successfully built deepdefacer
Installing collected packages: SimpleITK, deepdefacer
  Found existing installation: deepdefacer 1.0.5
    Uninstalling deepdefacer-1.0.5:
      Successfully uninstalled deepdefacer-1.0.5
Successfully installed SimpleITK-1.2.0 deepdefacer-2.0.4
```

```
me@christop ~ $ ls -al /c/users/me/miniconda3/lib/site-packages/deepdefacer/
total 5836
drwxr-xr-x 1 me 197609       0 Jan  9 00:39 ./
drwxr-xr-x 1 me 197609       0 Jan  9 00:39 ../
-rw-r--r-- 1 me 197609       0 Jan  9 00:38 __init__.py
drwxr-xr-x 1 me 197609       0 Jan  9 00:39 __pycache__/
-rw-r--r-- 1 me 197609    4085 Jan  9 00:38 defacer.py
-rw-r--r-- 1 me 197609    5357 Jan  9 00:38 defacer_utils.py
-rw-r--r-- 1 me 197609 5757336 Jan  9 00:38 model.hdf5
```

**Comment by AKhazane** [comment]
Hmm, this might be a pathing issue with Python 3 because `defacer_utils.py` is clearly present in your `deepdefacer` folder. Let me investigate this and push up a fix later today.

**Comment by AKhazane** [comment]
Ok, I think I was able to fix this issue - I just needed to specify a relative at the top of `defacer.py` file.

Also, just as a heads up, please use Python <= 3.6. Apparently Python 3.7 is currently in beta testing and it currently has many issues with tensorflow + keras. 

I'll make sure to write up all of the requirements on a README.md soon.
