### ISSUE TITLE
ImportError: `load_model` requires h5py

### ISSUE THREAD

**Issue by chrisfilo** [AKhazane/DeepDeface#4]
2.0.8 installed via pip from pypi 
```
Traceback (most recent call last):
  File "c:\users\me\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\Miniconda3\Scripts\deepdefacer.exe\__main__.py", line 9, in <module>
  File "c:\users\me\miniconda3\lib\site-packages\deepdefacer\defacer.py", line 55, in deface_3D_MRI
    deepdeface_model = load_model(model_file_path, custom_objects={'dice_coefficient': dice_coefficient})
  File "c:\users\me\miniconda3\lib\site-packages\keras\engine\saving.py", line 414, in load_model
    raise ImportError('`load_model` requires h5py.')
ImportError: `load_model` requires h5py.
```

Might be good to add CircleCI integration doing a smoke test on sample data in a clean environment to avoid such issues in the future.

**Comment by chrisfilo** [comment]
This might be an issue with my system.
